Traceback (most recent call last):
  File "C:\Users\B00460204\OneDrive - Ulster University\Phd - FPGA acceleration in genomics\2020-21 MainResearch\Seed_generation\rapid-SMEM\Rapid-SMEM\gnb_seed_generation_2\main.py", line 125, in <module>
    main()
  File "C:\Users\B00460204\OneDrive - Ulster University\Phd - FPGA acceleration in genomics\2020-21 MainResearch\Seed_generation\rapid-SMEM\Rapid-SMEM\gnb_seed_generation_2\main.py", line 78, in main
    training_flag, training_data = training_data_obj.generate_training_data(reference_genome_file, training_iterations) #will gen index if does not already exsist
  File "C:\Users\B00460204\OneDrive - Ulster University\Phd - FPGA acceleration in genomics\2020-21 MainResearch\Seed_generation\rapid-SMEM\Rapid-SMEM\gnb_seed_generation_2\gen_training_data.py", line 102, in generate_training_data
    training_set = generate_labeled_training_data(index, training_iterations)
  File "C:\Users\B00460204\OneDrive - Ulster University\Phd - FPGA acceleration in genomics\2020-21 MainResearch\Seed_generation\rapid-SMEM\Rapid-SMEM\gnb_seed_generation_2\gen_training_data.py", line 12, in generate_labeled_training_data
    for i in range(0,repetitions):
TypeError: 'str' object cannot be interpreted as an integer