2022-02-11 12:30:13,224 INFO    MainThread:16828 [wandb_setup.py:_flush():75] Loading settings from C:\Users\B00460204\.config\wandb\settings
2022-02-11 12:30:13,224 INFO    MainThread:16828 [wandb_setup.py:_flush():75] Loading settings from C:\Users\B00460204\OneDrive - Ulster University\Phd - FPGA acceleration in genomics\2020-21 MainResearch\Seed_generation\rapid-SMEM\Rapid-SMEM\gnb_seed_generation\wandb\settings
2022-02-11 12:30:13,224 INFO    MainThread:16828 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-02-11 12:30:13,224 INFO    MainThread:16828 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': 'gnb_seed_generation\\main.py', 'program': 'C:\\Users\\B00460204\\OneDrive - Ulster University\\Phd - FPGA acceleration in genomics\\2020-21 MainResearch\\Seed_generation\\rapid-SMEM\\Rapid-SMEM\\gnb_seed_generation\\main.py'}
2022-02-11 12:30:13,224 INFO    MainThread:16828 [wandb_init.py:_log_setup():386] Logging user logs to C:\Users\B00460204\OneDrive - Ulster University\Phd - FPGA acceleration in genomics\2020-21 MainResearch\Seed_generation\rapid-SMEM\Rapid-SMEM\gnb_seed_generation\wandb\run-20220211_123013-2rk7z8fo\logs\debug.log
2022-02-11 12:30:13,224 INFO    MainThread:16828 [wandb_init.py:_log_setup():387] Logging internal logs to C:\Users\B00460204\OneDrive - Ulster University\Phd - FPGA acceleration in genomics\2020-21 MainResearch\Seed_generation\rapid-SMEM\Rapid-SMEM\gnb_seed_generation\wandb\run-20220211_123013-2rk7z8fo\logs\debug-internal.log
2022-02-11 12:30:13,232 INFO    MainThread:16828 [wandb_init.py:init():420] calling init triggers
2022-02-11 12:30:13,232 INFO    MainThread:16828 [wandb_init.py:init():425] wandb.init called with sweep_config: {}
config: {}
2022-02-11 12:30:13,233 INFO    MainThread:16828 [wandb_init.py:init():471] starting backend
2022-02-11 12:30:13,233 INFO    MainThread:16828 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=spawn, using: spawn
2022-02-11 12:30:13,241 INFO    MainThread:16828 [backend.py:ensure_launched():219] starting backend process...
2022-02-11 12:30:13,477 INFO    MainThread:16828 [backend.py:ensure_launched():224] started backend process with pid: 4636
2022-02-11 12:30:13,481 INFO    MainThread:16828 [wandb_init.py:init():480] backend started and connected
2022-02-11 12:30:13,482 INFO    MainThread:16828 [wandb_init.py:init():550] updated telemetry
2022-02-11 12:30:13,622 INFO    MainThread:16828 [wandb_init.py:init():581] communicating current version
2022-02-11 12:30:15,482 INFO    MainThread:16828 [wandb_init.py:init():586] got version response 
2022-02-11 12:30:15,483 INFO    MainThread:16828 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-02-11 12:30:15,869 INFO    MainThread:16828 [wandb_init.py:init():624] starting run threads in backend
2022-02-11 12:30:16,298 INFO    MainThread:16828 [wandb_run.py:_console_start():1827] atexit reg
2022-02-11 12:30:16,304 INFO    MainThread:16828 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2022-02-11 12:30:16,304 INFO    MainThread:16828 [wandb_run.py:_redirect():1738] Wrapping output streams.
2022-02-11 12:30:16,309 INFO    MainThread:16828 [wandb_run.py:_redirect():1762] Redirects installed.
2022-02-11 12:30:16,309 INFO    MainThread:16828 [wandb_init.py:init():651] run started, returning control to user process
2022-02-11 12:30:21,322 INFO    MainThread:16828 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 1
2022-02-11 12:30:21,324 INFO    MainThread:16828 [wandb_run.py:_restore():1769] restore
2022-02-11 12:30:24,307 ERROR   MainThread:16828 [wandb_run.py:_atexit_cleanup():1815] Problem finishing run
Traceback (most recent call last):
  File "C:\Users\B00460204\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\wandb\sdk\wandb_run.py", line 1805, in _atexit_cleanup
    self._on_finish()
  File "C:\Users\B00460204\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\wandb\sdk\wandb_run.py", line 1951, in _on_finish
    self.history._flush()
  File "C:\Users\B00460204\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\wandb\sdk\wandb_history.py", line 59, in _flush
    self._callback(row=self._data, step=self._step)
  File "C:\Users\B00460204\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\wandb\sdk\wandb_run.py", line 1027, in _history_callback
    self._backend.interface.publish_history(
  File "C:\Users\B00460204\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\wandb\sdk\interface\interface.py", line 505, in publish_history
    item.value_json = json_dumps_safer_history(v)  # type: ignore
  File "C:\Users\B00460204\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\wandb\util.py", line 761, in json_dumps_safer_history
    return json.dumps(obj, cls=WandBHistoryJSONEncoder, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\B00460204\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\wandb\util.py", line 728, in default
    return json.JSONEncoder.default(self, obj)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type set is not JSON serializable
